version: '3'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
      - MSSQL_PID=Developer