using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace GeoPET.Migrations
{
    /// <inheritdoc />
    public partial class initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Breeds",
                columns: table => new
                {
                    BreedId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Breeds", x => x.BreedId);
                });

            migrationBuilder.CreateTable(
                name: "PetCarers",
                columns: table => new
                {
                    PetCarerId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Email = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ZipCode = table.Column<string>(type: "nvarchar(8)", maxLength: 8, nullable: false),
                    PasswordHash = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PetCarers", x => x.PetCarerId);
                });

            migrationBuilder.CreateTable(
                name: "Pets",
                columns: table => new
                {
                    PetId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Age = table.Column<int>(type: "int", nullable: false),
                    Weight = table.Column<double>(type: "float", nullable: false),
                    BreedId = table.Column<int>(type: "int", nullable: true),
                    LocalizationHash = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PetCarerId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pets", x => x.PetId);
                    table.ForeignKey(
                        name: "FK_Pets_Breeds_BreedId",
                        column: x => x.BreedId,
                        principalTable: "Breeds",
                        principalColumn: "BreedId");
                    table.ForeignKey(
                        name: "FK_Pets_PetCarers_PetCarerId",
                        column: x => x.PetCarerId,
                        principalTable: "PetCarers",
                        principalColumn: "PetCarerId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Breeds",
                columns: new[] { "BreedId", "Name" },
                values: new object[,]
                {
                    { 1, "Affenpinscher" },
                    { 2, "Afghan Hound" },
                    { 3, "Africanis" },
                    { 4, "Aidi" },
                    { 5, "Airedale Terrier" },
                    { 6, "Akbash" },
                    { 7, "Akita" },
                    { 8, "Aksaray Malaklisi" },
                    { 9, "Alano Espaol" },
                    { 10, "Alapaha Blue Blood Bulldog" },
                    { 11, "Alaskan Klee Kai" },
                    { 12, "Alaskan Malamute" },
                    { 13, "Alaskan husky" },
                    { 14, "Alaunt" },
                    { 15, "Alopekis" },
                    { 16, "Alpine Dachsbracke" },
                    { 17, "Alpine Mastiff" },
                    { 18, "American Alsatian" },
                    { 19, "American Bulldog" },
                    { 20, "American Bully" },
                    { 21, "American Cocker Spaniel" },
                    { 22, "American English Coonhound" },
                    { 23, "American Eskimo Dog" },
                    { 24, "American Foxhound" },
                    { 25, "American Hairless Terrier" },
                    { 26, "American Pit Bull Terrier" },
                    { 27, "American Staffordshire Terrier" },
                    { 28, "American Water Spaniel" },
                    { 29, "Andalusian Hound" },
                    { 30, "AngloFranais de Petite Vnerie" },
                    { 31, "Appenzeller Sennenhund" },
                    { 32, "Argentine Polar Dog" },
                    { 33, "Ariegeois" },
                    { 34, "Armant" },
                    { 35, "Armenian Gampr dog" },
                    { 36, "Artois Hound" },
                    { 37, "Assyrian Mastiff" },
                    { 38, "Australian Bulldog" },
                    { 39, "Australian Cattle Dog" },
                    { 40, "Australian Kelpie" },
                    { 41, "Australian Shepherd" },
                    { 42, "Australian Stumpy Tail Cattle Dog" },
                    { 43, "Australian Terrier" },
                    { 44, "Austrian Black and Tan Hound" },
                    { 45, "Austrian Pinscher" },
                    { 46, "Azawakh" },
                    { 47, "Bakharwal dog" },
                    { 48, "Banjara Hound" },
                    { 49, "Barbado da Terceira" },
                    { 50, "Barbet" },
                    { 51, "Basenji" },
                    { 52, "Basque Shepherd Dog" },
                    { 53, "Basset Artsien Normand" },
                    { 54, "Basset Bleu de Gascogne" },
                    { 55, "Basset Fauve de Bretagne" },
                    { 56, "Basset Hound" },
                    { 57, "Bavarian Mountain Hound" },
                    { 58, "Bc H dog" },
                    { 59, "Beagle" },
                    { 60, "BeagleHarrier" },
                    { 61, "Bearded Collie" },
                    { 62, "Beauceron" },
                    { 63, "Bedlington Terrier" },
                    { 64, "Belgian Mastiff" },
                    { 65, "Belgian Shepherd" },
                    { 66, "Bergamasco Shepherd" },
                    { 67, "Berger Picard" },
                    { 68, "Bernese Mountain Dog" },
                    { 69, "Bichon Fris" },
                    { 70, "Biewer Terrier" },
                    { 71, "Billy" },
                    { 72, "Black Mouth Cur" },
                    { 73, "Black Norwegian Elkhound" },
                    { 74, "Black Russian Terrier" },
                    { 75, "Black and Tan Coonhound" },
                    { 76, "Black and Tan Terrier" },
                    { 77, "Bloodhound" },
                    { 78, "Blue Lacy" },
                    { 79, "Blue Paul Terrier" },
                    { 80, "Blue Picardy Spaniel" },
                    { 81, "Bluetick Coonhound" },
                    { 82, "Boerboel" },
                    { 83, "Bohemian Shepherd" },
                    { 84, "Bolognese" },
                    { 85, "Border Collie" },
                    { 86, "Border Terrier" },
                    { 87, "Borzoi" },
                    { 88, "Bosnian Coarsehaired Hound" },
                    { 89, "Boston Terrier" },
                    { 90, "Bouvier des Ardennes" },
                    { 91, "Bouvier des Flandres" },
                    { 92, "Boxer" },
                    { 93, "Boykin Spaniel" },
                    { 94, "Bracco Italiano" },
                    { 95, "Braque Dupuy" },
                    { 96, "Braque Francais" },
                    { 97, "Braque SaintGermain" },
                    { 98, "Braque dAuvergne" },
                    { 99, "Braque de lArige" },
                    { 100, "Braque du Bourbonnais" },
                    { 101, "Briard" },
                    { 102, "Briquet Griffon Venden" },
                    { 103, "Brittany" },
                    { 104, "Broholmer" },
                    { 105, "Bruno Jura Hound" },
                    { 106, "Brussels Griffon" },
                    { 107, "Buckhound" },
                    { 108, "Bucovina Shepherd Dog" },
                    { 109, "Bull Arab" },
                    { 110, "Bull Terrier" },
                    { 111, "Bull and terrier" },
                    { 112, "Bullbras" },
                    { 113, "Bulldog" },
                    { 114, "Bullenbeisser" },
                    { 115, "Bullmastiff" },
                    { 116, "Bully Kutta" },
                    { 117, "Burgos Pointer" },
                    { 118, "BuryatMongolian Wolfhound" },
                    { 119, "Ca M Mallorqu" },
                    { 120, "Ca de Bou" },
                    { 121, "Cairn Terrier" },
                    { 122, "Calupoh" },
                    { 123, "Campeiro Bulldog" },
                    { 124, "Can de Chira" },
                    { 125, "Can de Palleiro" },
                    { 126, "Canaan Dog" },
                    { 127, "Canadian Eskimo Dog" },
                    { 128, "Cane Corso" },
                    { 129, "Cane Paratore" },
                    { 130, "Cane di Oropa" },
                    { 131, "Cantabrian Water Dog" },
                    { 132, "Cardigan Welsh Corgi" },
                    { 133, "Carea Castellano Manchego" },
                    { 134, "Carea Leons" },
                    { 135, "Carolina Dog" },
                    { 136, "Carpathian Shepherd Dog" },
                    { 137, "Catahoula Leopard Dog" },
                    { 138, "Catalan Sheepdog" },
                    { 139, "Caucasian Shepherd Dog" },
                    { 140, "Cavalier King Charles Spaniel" },
                    { 141, "Central Asian Shepherd Dog" },
                    { 142, "Cesky Fousek" },
                    { 143, "Cesky Terrier" },
                    { 144, "Chesapeake Bay Retriever" },
                    { 145, "Chien Franais Blanc et Noir" },
                    { 146, "Chien Franais Blanc et Orange" },
                    { 147, "Chien Franais Tricolore" },
                    { 148, "Chiengris" },
                    { 149, "Chihuahua" },
                    { 150, "Chilean Terrier" },
                    { 151, "Chinese Crested Dog" },
                    { 152, "Chinook" },
                    { 153, "Chippiparai" },
                    { 154, "Chiribaya Dog" },
                    { 155, "Chongqing dog" },
                    { 156, "Chortai" },
                    { 157, "Chow Chow" },
                    { 158, "Chukotka sled dog" },
                    { 159, "Cimarrn Uruguayo" },
                    { 160, "Cirneco dellEtna" },
                    { 161, "Clumber Spaniel" },
                    { 162, "Co Fila de So Miguel" },
                    { 163, "Co da Serra de Aires" },
                    { 164, "Co de Castro Laboreiro" },
                    { 165, "Co de Gado Transmontano" },
                    { 166, "Colombian fino hound" },
                    { 167, "Continental bulldog" },
                    { 168, "Cordoba Fighting Dog" },
                    { 169, "Coton de Tulear" },
                    { 170, "Cretan Hound" },
                    { 171, "Croatian Sheepdog" },
                    { 172, "Cumberland Sheepdog" },
                    { 173, "Cur" },
                    { 174, "CurlyCoated Retriever" },
                    { 175, "Cursinu" },
                    { 176, "Czechoslovakian Wolfdog" },
                    { 177, "Dachshund" },
                    { 178, "Dalbo dog" },
                    { 179, "Dalmatian" },
                    { 180, "Dandie Dinmont Terrier" },
                    { 181, "Danish Spitz" },
                    { 182, "DanishSwedish Farmdog" },
                    { 183, "Denmark Feist" },
                    { 184, "Dingo note " },
                    { 185, "Dobermann" },
                    { 186, "Dogo Argentino" },
                    { 187, "Dogo Guatemalteco" },
                    { 188, "Dogo Sardesco" },
                    { 189, "Dogo cubano" },
                    { 190, "Dogue Brasileiro" },
                    { 191, "Dogue de Bordeaux" },
                    { 192, "Donggyeongi" },
                    { 193, "Drentse Patrijshond" },
                    { 194, "Drever" },
                    { 195, "Dumfriesshire Black and Tan Foxhound" },
                    { 196, "Dunker" },
                    { 197, "Dutch Shepherd" },
                    { 198, "Dutch Smoushond" },
                    { 199, "East European Shepherd" },
                    { 200, "East Siberian Laika" },
                    { 201, "Ecuadorian Hairless Dog" },
                    { 202, "English Cocker Spaniel" },
                    { 203, "English Foxhound" },
                    { 204, "English Mastiff" },
                    { 205, "English Setter" },
                    { 206, "English Shepherd" },
                    { 207, "English Springer Spaniel" },
                    { 208, "English Toy Terrier Black  Tan" },
                    { 209, "English Water Spaniel" },
                    { 210, "English White Terrier" },
                    { 211, "Entlebucher Mountain Dog" },
                    { 212, "Estonian Hound" },
                    { 213, "Estrela Mountain Dog" },
                    { 214, "Eurasier" },
                    { 215, "Extinct varieties and types" },
                    { 216, "Field Spaniel" },
                    { 217, "Fila Brasileiro" },
                    { 218, "Fila da Terceira" },
                    { 219, "Finnish Hound" },
                    { 220, "Finnish Lapphund" },
                    { 221, "Finnish Spitz" },
                    { 222, "FlatCoated Retriever" },
                    { 223, "French Bulldog" },
                    { 224, "French Spaniel" },
                    { 225, "Fuegian dog" },
                    { 226, "Galgo Espaol" },
                    { 227, "Garafian Shepherd" },
                    { 228, "Gascon Saintongeois" },
                    { 229, "Georgian Shepherd" },
                    { 230, "German Hound" },
                    { 231, "German Longhaired Pointer" },
                    { 232, "German Pinscher" },
                    { 233, "German Roughhaired Pointer" },
                    { 234, "German Shepherd" },
                    { 235, "German Shorthaired Pointer" },
                    { 236, "German Spaniel" },
                    { 237, "German Spitz" },
                    { 238, "German Wirehaired Pointer" },
                    { 239, "Giant Schnauzer" },
                    { 240, "Glen of Imaal Terrier" },
                    { 241, "Goczy Polski" },
                    { 242, "Golden Retriever" },
                    { 243, "Gordon Setter" },
                    { 244, "Grand AngloFranais Blanc et Noir" },
                    { 245, "Grand AngloFranais Blanc et Orange" },
                    { 246, "Grand AngloFranais Tricolore" },
                    { 247, "Grand Basset Griffon Venden" },
                    { 248, "Grand Bleu de Gascogne" },
                    { 249, "Grand Fauve de Bretagne" },
                    { 250, "Grand Griffon Venden" },
                    { 251, "Great Dane" },
                    { 252, "Greater Swiss Mountain Dog" },
                    { 253, "Greek Harehound" },
                    { 254, "Greek Shepherd" },
                    { 255, "Greenland Dog" },
                    { 256, "Greyhound" },
                    { 257, "Griffon Bleu de Gascogne" },
                    { 258, "Griffon Fauve de Bretagne" },
                    { 259, "Griffon Nivernais" },
                    { 260, "Gull Dong" },
                    { 261, "Gull Terrier" },
                    { 262, "Halden Hound" },
                    { 263, "Halls Heeler" },
                    { 264, "Hamiltonstvare" },
                    { 265, "Hanover Hound" },
                    { 266, "Hare Indian Dog" },
                    { 267, "Harrier" },
                    { 268, "Havanese" },
                    { 269, "Hawaiian Poi Dog" },
                    { 270, "Hierran Wolfdog" },
                    { 271, "Himalayan Sheepdog" },
                    { 272, "Hllefors Elkhound" },
                    { 273, "Hmong bobtail dog" },
                    { 274, "Hokkaido" },
                    { 275, "Hovawart" },
                    { 276, "Huntaway" },
                    { 277, "Hygen Hound" },
                    { 278, "Ibizan Hound" },
                    { 279, "Icelandic Sheepdog" },
                    { 280, "Indian Spitz" },
                    { 281, "Indian pariah dog" },
                    { 282, "Irish Red and White Setter" },
                    { 283, "Irish Setter" },
                    { 284, "Irish Terrier" },
                    { 285, "Irish Water Spaniel" },
                    { 286, "Irish Wolfhound" },
                    { 287, "Istrian Coarsehaired Hound" },
                    { 288, "Istrian Shorthaired Hound" },
                    { 289, "Italian Greyhound" },
                    { 290, "Jack Russell Terrier" },
                    { 291, "Jagdterrier" },
                    { 292, "Japanese Chin" },
                    { 293, "Japanese Spitz" },
                    { 294, "Japanese Terrier" },
                    { 295, "Jindo" },
                    { 296, "Jonangi" },
                    { 297, "Kai Ken" },
                    { 298, "Kaikadi" },
                    { 299, "Kangal Shepherd Dog" },
                    { 300, "Kanni" },
                    { 301, "Karakachan dog" },
                    { 302, "Karelian Bear Dog" },
                    { 303, "Kars" },
                    { 304, "Karst Shepherd" },
                    { 305, "Keeshond" },
                    { 306, "Kerry Beagle" },
                    { 307, "Kerry Blue Terrier" },
                    { 308, "Khala " },
                    { 309, "King Charles Spaniel" },
                    { 310, "King Shepherd" },
                    { 311, "Kings White Hound" },
                    { 312, "Kintamani" },
                    { 313, "Kishu" },
                    { 314, "Kokoni" },
                    { 315, "Kombai" },
                    { 316, "Komondor" },
                    { 317, "Kooikerhondje" },
                    { 318, "Koolie" },
                    { 319, "Koyun dog" },
                    { 320, "Kromfohrlnder" },
                    { 321, "Kuchi" },
                    { 322, "Kunming dog" },
                    { 323, "Kur" },
                    { 324, "Kuvasz" },
                    { 325, "Labrador Retriever" },
                    { 326, "Lagotto Romagnolo" },
                    { 327, "Lakeland Terrier" },
                    { 328, "Lancashire Heeler" },
                    { 329, "Landseer" },
                    { 330, "Lapponian Herder" },
                    { 331, "Lapponian Shepherd" },
                    { 332, "Large Mnsterlnder" },
                    { 333, "Leonberger" },
                    { 334, "Levriero Sardo" },
                    { 335, "Lhasa Apso" },
                    { 336, "Liangshan Dog" },
                    { 337, "Limer" },
                    { 338, "Lithuanian Hound" },
                    { 339, "Lobito Herreo" },
                    { 340, "Lupo Italiano" },
                    { 341, "Lwchen" },
                    { 342, "Mackenzie River husky" },
                    { 343, "Magyar agr" },
                    { 344, "Mahratta Greyhound" },
                    { 345, "Maltese" },
                    { 346, "Manchester Terrier" },
                    { 347, "Maneto" },
                    { 348, "MaremmanoAbruzzese Sheepdog" },
                    { 349, "Marquesan Dog" },
                    { 350, "McNab dog" },
                    { 351, "Miniature American Shepherd" },
                    { 352, "Miniature Bull Terrier" },
                    { 353, "Miniature Fox Terrier" },
                    { 354, "Miniature Pinscher" },
                    { 355, "Miniature Schnauzer" },
                    { 356, "Molossus" },
                    { 357, "Molossus of Epirus" },
                    { 358, "Montenegrin Mountain Hound" },
                    { 359, "Moscow Water Dog" },
                    { 360, "Mountain Cur" },
                    { 361, "Mountain Feist" },
                    { 362, "Mucuchies" },
                    { 363, "Mudhol Hound" },
                    { 364, "Mudi" },
                    { 365, "Neapolitan Mastiff" },
                    { 366, "Nenets Herding Laika" },
                    { 367, "New Guinea singing dog" },
                    { 368, "New Zealand Heading Dog" },
                    { 369, "Newfoundland" },
                    { 370, "Norfolk Spaniel" },
                    { 371, "Norfolk Terrier" },
                    { 372, "Norman Hound" },
                    { 373, "Norrbottenspets" },
                    { 374, "North Country Beagle" },
                    { 375, "Northern Inuit Dog" },
                    { 376, "Norwegian Buhund" },
                    { 377, "Norwegian Elkhound" },
                    { 378, "Norwegian Lundehund" },
                    { 379, "Norwich Terrier" },
                    { 380, "Nova Scotia Duck Tolling Retriever" },
                    { 381, "Old Croatian Sighthound" },
                    { 382, "Old Danish Pointer" },
                    { 383, "Old English Bulldog" },
                    { 384, "Old English Sheepdog" },
                    { 385, "Old English Terrier" },
                    { 386, "Old Spanish Pointer" },
                    { 387, "Old Welsh Grey Sheepdog" },
                    { 388, "Olde English Bulldogge" },
                    { 389, "Otterhound" },
                    { 390, "Pachon Navarro" },
                    { 391, "Paisley Terrier" },
                    { 392, "Pampas Deerhound" },
                    { 393, "Papillon" },
                    { 394, "Parson Russell Terrier" },
                    { 395, "Pastore della Lessinia e del Lagorai" },
                    { 396, "Patagonian Sheepdog" },
                    { 397, "Patterdale Terrier" },
                    { 398, "Pekingese" },
                    { 399, "Pembroke Welsh Corgi" },
                    { 400, "Perro Majorero" },
                    { 401, "Perro de Pastor Mallorquin" },
                    { 402, "Perro de Presa Canario" },
                    { 403, "Perro de Presa Mallorquin" },
                    { 404, "Peruvian Inca Orchid" },
                    { 405, "Petit Basset Griffon Venden" },
                    { 406, "Petit Bleu de Gascogne" },
                    { 407, "Phalne" },
                    { 408, "Pharaoh Hound" },
                    { 409, "Phu Quoc Ridgeback" },
                    { 410, "Picardy Spaniel" },
                    { 411, "Plott Hound" },
                    { 412, "Plummer Terrier" },
                    { 413, "Podenco Canario" },
                    { 414, "Podenco Valenciano" },
                    { 415, "Pointer" },
                    { 416, "Poitevin" },
                    { 417, "Polish Greyhound" },
                    { 418, "Polish Hound" },
                    { 419, "Polish Lowland Sheepdog" },
                    { 420, "Polish Tatra Sheepdog" },
                    { 421, "Polynesian Dog" },
                    { 422, "Pomeranian" },
                    { 423, "PontAudemer Spaniel" },
                    { 424, "Poodle" },
                    { 425, "Porcelaine" },
                    { 426, "Portuguese Podengo" },
                    { 427, "Portuguese Pointer" },
                    { 428, "Portuguese Water Dog" },
                    { 429, "Posavac Hound" },
                    { 430, "Prask Krysak" },
                    { 431, "Pshdar dog" },
                    { 432, "Pudelpointer" },
                    { 433, "Pug" },
                    { 434, "Puli" },
                    { 435, "Pumi" },
                    { 436, "Pungsan dog" },
                    { 437, "Pyrenean Mastiff" },
                    { 438, "Pyrenean Mountain Dog" },
                    { 439, "Pyrenean Sheepdog" },
                    { 440, "Rache" },
                    { 441, "Rafeiro do Alentejo" },
                    { 442, "Rajapalayam" },
                    { 443, "Rampur Greyhound" },
                    { 444, "Rastreador Brasileiro" },
                    { 445, "Rat Terrier" },
                    { 446, "Ratonero Bodeguero Andaluz" },
                    { 447, "Ratonero Mallorquin" },
                    { 448, "Ratonero Murciano" },
                    { 449, "Ratonero Valenciano" },
                    { 450, "Redbone Coonhound" },
                    { 451, "Rhodesian Ridgeback" },
                    { 452, "Romanian Mioritic Shepherd Dog" },
                    { 453, "Romanian Raven Shepherd Dog" },
                    { 454, "Rottweiler" },
                    { 455, "Rough Collie" },
                    { 456, "Russian Spaniel" },
                    { 457, "Russian Toy" },
                    { 458, "RussoEuropean Laika" },
                    { 459, "Ryukyu Inu" },
                    { 460, "Saarloos Wolfdog" },
                    { 461, "Sabueso Espaol" },
                    { 462, "Saint Bernard" },
                    { 463, "Saint Hubert Jura Hound" },
                    { 464, "Saint Johns water dog" },
                    { 465, "SaintUsuge Spaniel" },
                    { 466, "Sakhalin Husky" },
                    { 467, "Salish Wool Dog" },
                    { 468, "Saluki" },
                    { 469, "Samoyed" },
                    { 470, "Sapsali" },
                    { 471, "Sarabi dog" },
                    { 472, "Sardinian Shepherd Dog" },
                    { 473, "Schapendoes" },
                    { 474, "Schillerstvare" },
                    { 475, "Schipperke" },
                    { 476, "Schweizer Laufhund" },
                    { 477, "Schweizerischer Niederlaufhund" },
                    { 478, "Scottish Deerhound" },
                    { 479, "Scottish Terrier" },
                    { 480, "Sealyham Terrier" },
                    { 481, "Segugio Italiano" },
                    { 482, "Segugio Maremmano" },
                    { 483, "Segugio dellAppennino" },
                    { 484, "Serbian Hound" },
                    { 485, "Serbian Tricolour Hound" },
                    { 486, "Serrano Bulldog" },
                    { 487, "Shar Pei" },
                    { 488, "Shetland Sheepdog" },
                    { 489, "Shiba Inu" },
                    { 490, "Shih Tzu" },
                    { 491, "Shikoku" },
                    { 492, "Shiloh Shepherd" },
                    { 493, "Siberian Husky" },
                    { 494, "Silken Windhound" },
                    { 495, "Silky Terrier" },
                    { 496, "Sinhala Hound" },
                    { 497, "Skye Terrier" },
                    { 498, "Sleuth hound" },
                    { 499, "Sloughi" },
                    { 500, "Slovakian Wirehaired Pointer" },
                    { 501, "Slovensk Cuvac" },
                    { 502, "Slovensk Kopov" },
                    { 503, "Smalandstvare" },
                    { 504, "Small Greek domestic dog" },
                    { 505, "Small Mnsterlnder" },
                    { 506, "Smooth Collie" },
                    { 507, "Smooth Fox Terrier" },
                    { 508, "SoftCoated Wheaten Terrier" },
                    { 509, "South Russian Ovcharka" },
                    { 510, "Southern Hound" },
                    { 511, "Spanish Mastiff" },
                    { 512, "Spanish Water Dog" },
                    { 513, "Spinone Italiano" },
                    { 514, "Sporting Lucas Terrier" },
                    { 515, "Stabyhoun" },
                    { 516, "Staffordshire Bull Terrier" },
                    { 517, "Staghound" },
                    { 518, "Standard Schnauzer" },
                    { 519, "Stephens Stock" },
                    { 520, "Styrian Coarsehaired Hound" },
                    { 521, "Sussex Spaniel" },
                    { 522, "Swedish Elkhound" },
                    { 523, "Swedish Lapphund" },
                    { 524, "Swedish Vallhund" },
                    { 525, "Swedish White Elkhound" },
                    { 526, "Swinford Bandog" },
                    { 527, "Tahitian Dog" },
                    { 528, "Tahltan Bear Dog" },
                    { 529, "Taigan" },
                    { 530, "Taiwan Dog" },
                    { 531, "Talbot Hound" },
                    { 532, "Tamaskan Dog" },
                    { 533, "Tang Dog" },
                    { 534, "Tazy" },
                    { 535, "Teddy Roosevelt Terrier" },
                    { 536, "Telomian" },
                    { 537, "Tenterfield Terrier" },
                    { 538, "Terrier Brasileiro" },
                    { 539, "Tesem" },
                    { 540, "Thai Bangkaew Dog" },
                    { 541, "Thai Ridgeback" },
                    { 542, "Tibetan Kyi Apso" },
                    { 543, "Tibetan Mastiff" },
                    { 544, "Tibetan Spaniel" },
                    { 545, "Tibetan Terrier" },
                    { 546, "Tonya Finosu" },
                    { 547, "Torkuz" },
                    { 548, "Tornjak" },
                    { 549, "Tosa Inu" },
                    { 550, "Toy Fox Terrier" },
                    { 551, "Toy Manchester Terrier" },
                    { 552, "Transylvanian Hound" },
                    { 553, "Treeing Cur" },
                    { 554, "Treeing Feist" },
                    { 555, "Treeing Tennessee Brindle" },
                    { 556, "Treeing Walker Coonhound" },
                    { 557, "Trigg Hound" },
                    { 558, "Tyrolean Hound" },
                    { 559, "Vikhan" },
                    { 560, "Villano de Las Encartaciones" },
                    { 561, "Villanuco de Las Encartaciones" },
                    { 562, "Vizsla" },
                    { 563, "Volpino Italiano" },
                    { 564, "Weimaraner" },
                    { 565, "Welsh Hound" },
                    { 566, "Welsh Sheepdog" },
                    { 567, "Welsh Springer Spaniel" },
                    { 568, "Welsh Terrier" },
                    { 569, "West Country Harrier" },
                    { 570, "West Highland White Terrier" },
                    { 571, "West Siberian Laika" },
                    { 572, "Westphalian Dachsbracke" },
                    { 573, "Wetterhoun" },
                    { 574, "Whippet" },
                    { 575, "White Shepherd" },
                    { 576, "White Swiss Shepherd Dog" },
                    { 577, "Wire Fox Terrier" },
                    { 578, "Wirehaired Pointing Griffon" },
                    { 579, "Wirehaired Vizsla" },
                    { 580, "Xiasi Dog" },
                    { 581, "Xoloitzcuintle" },
                    { 582, "Yakutian Laika" },
                    { 583, "Yorkshire Terrier" },
                    { 584, "Zerdava" }
                });

            migrationBuilder.InsertData(
                table: "PetCarers",
                columns: new[] { "PetCarerId", "Email", "Name", "PasswordHash", "ZipCode" },
                values: new object[] { 1, "johndoe@email.com", "John Doe", "VlKqPxGgnUZQSClj9S6ZA2ubZdyDuxsqqVgFBAvZ57aMLABXA45YJH5ewrntl4klJ8vm7lK+d3yQnFOVegdzoPTgiy5AubUzL6lBqDxT1sZC7pVbXLsgyUBaZ1mr/j8k/Y+XQxZ9M8mfLfQPJeeVrxiLfQ5wgT0aXTqfFv68tBdvD6V0ZMbnwcVrijZq+bdurp+GV1+wqDshGVpBh3FpI8WRVyfxzfBfiUWrZfuvc5t+srZqM8MUZCVsTHNyvCBxBd1k0AWKTUmbnLTIERqTzZF6lq/C/9OOiPPd0c2hM/+W1QSWs8vYOFT5Ogf0D087IEbUSb1pOcgLa877imMv9Q==", "05426200" });

            migrationBuilder.InsertData(
                table: "Pets",
                columns: new[] { "PetId", "Age", "BreedId", "LocalizationHash", "Name", "PetCarerId", "Weight" },
                values: new object[] { 1, 3, 26, null, "Bailey", 1, 5.5 });

            migrationBuilder.CreateIndex(
                name: "IX_PetCarers_Email",
                table: "PetCarers",
                column: "Email",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Pets_BreedId",
                table: "Pets",
                column: "BreedId");

            migrationBuilder.CreateIndex(
                name: "IX_Pets_PetCarerId",
                table: "Pets",
                column: "PetCarerId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Pets");

            migrationBuilder.DropTable(
                name: "Breeds");

            migrationBuilder.DropTable(
                name: "PetCarers");
        }
    }
}
